export interface caseCreationStoreType {
    caseId: string,
    caseName: string,
    description: string,
    collaboratorUserId: string[],
    personNumber: string[],
    // young: boolean,
    // adult: boolean,
    // male: boolean,
    // female: boolean,
    // hairLong: boolean,
    // hairShort: boolean,
    // upperLengthLong: boolean,
    // upperLengthShort: boolean,
    // lowerLengthLong: boolean,
    // lowerLengthShort: boolean,
    // pants: boolean,
    // skirt: boolean,
    // bag: boolean,
    // hat: boolean,
    // helmet: boolean,
    // backBag: boolean,
    generalAtt: any,
    colorAtt: any
    // upperColorBlack: boolean,
    // upperColorWhite: boolean,
    // upperColorRed: boolean,
    // upperColorGreen: boolean,
    // upperColorYellow: boolean,
    // upperColorOrange: boolean,
    // upperColorPurple: boolean,
    // upperColorPink: boolean,
    // upperColorBlue: boolean,
    // upperColorGray: boolean,
    // lowerColorBlack: boolean,
    // lowerColorWhite: boolean,
    // lowerColorRed: boolean,
    // lowerColorGreen: boolean,
    // lowerColorYellow: boolean,
    // lowerColorOrange: boolean,
    // lowerColorPurple: boolean,
    // lowerColorPink: boolean,
    // lowerColorBlue: boolean,
    // lowerColorGray: boolean,
    startTime: number,
    endTime: number,
    tags: string[]
}

export interface UserStoreState {
    userID: string;
    // define other properties here
  }

  export interface analyzeFilterType {
    caseId: string,
    caseName: string,
    description: string,
    collaboratorUserId: string[],
    personNumber: string[],
    // young: boolean,
    // adult: boolean,
    // male: boolean,
    // female: boolean,
    // hairLong: boolean,
    // hairShort: boolean,
    // upperLengthLong: boolean,
    // upperLengthShort: boolean,
    // lowerLengthLong: boolean,
    // lowerLengthShort: boolean,
    // pants: boolean,
    // skirt: boolean,
    // bag: boolean,
    // hat: boolean,
    // helmet: boolean,
    // backBag: boolean,
    generalAtt: any,
    colorAtt: any
    // upperColorBlack: boolean,
    // upperColorWhite: boolean,
    // upperColorRed: boolean,
    // upperColorGreen: boolean,
    // upperColorYellow: boolean,
    // upperColorOrange: boolean,
    // upperColorPurple: boolean,
    // upperColorPink: boolean,
    // upperColorBlue: boolean,
    // upperColorGray: boolean,
    // lowerColorBlack: boolean,
    // lowerColorWhite: boolean,
    // lowerColorRed: boolean,
    // lowerColorGreen: boolean,
    // lowerColorYellow: boolean,
    // lowerColorOrange: boolean,
    // lowerColorPurple: boolean,
    // lowerColorPink: boolean,
    // lowerColorBlue: boolean,
    // lowerColorGray: boolean,
}